name: Test Telegram Bot Run

on:
  workflow_dispatch:  # позволяет запускать вручную через GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        run: python project.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

      - name: Commit changes to database
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add news.db
          git commit -m "Update news.db [skip ci]" || echo "No changes to commit"
          git push
